name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo "ssh_key_pk : ${{ secrets.ssh_key_pk }}"

    - name: Deploy to Server via scp
      uses: horochx/deploy-via-scp@master
      with:
        local: dist
        remote: "dist"
        host: "139.198.13.100"
        port: "10003"
        user: "jiker_deployer"
        key: ${{ secrets.SSH_KEY_PK	}}

    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: "139.198.13.100"
        port: "10003"
        username: "jiker_deployer"
        key: ${{ secrets.SSH_KEY_PK }}
        script: |
          whoami
          ls -al
          echo "abc" >> aaa.txt
      

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PK	}}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "dist/"
        REMOTE_HOST: "139.198.13.100"
        REMOTE_USER: "jiker_deployer"
        REMOTE_PORT: "10003"
        TARGET: "dist/"